# SPDX-FileCopyrightText: © 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: MIT

"""
NuRec Coordinate Comparison Tests

Integration tests comparing coordinate transform results with NuRec reference data.
Validates that the DGGT coordinate transform module matches NuRec's transformation chain.
"""

import pytest
import numpy as np
import json
import os
from pathlib import Path
import sys

# Add parent directories to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from dggt_server.coordinate_transform import CoordinateTransform


class TestNuRecCoordinateComparison:
    """Compare coordinate transforms with NuRec reference data"""

    @pytest.fixture
    def nurec_reference_data(self):
        """Load NuRec reference data from test fixtures"""
        ref_path = Path(__file__).parent.parent / "test_data" / "nurec_reference" / "coordinate_transforms.json"
        if ref_path.exists():
            with open(ref_path) as f:
                return json.load(f)
        return None

    @pytest.fixture
    def sample_carla_pose(self):
        """Sample CARLA camera pose matrix for basic tests"""
        # 4x4 pose matrix: rotation + translation
        # CARLA coordinate: X=Forward, Y=Right, Z=Up
        # Use simple rotation (no pitch) for roundtrip test stability
        pose = np.array([
            [ 1.0,  0.0,  0.0,  10.0],  # Forward 10m
            [ 0.0,  1.0,  0.0,   5.0],  # Right 5m
            [ 0.0,  0.0,  1.0,   2.0],  # Up 2m
            [ 0.0,  0.0,  0.0,   1.0]
        ], dtype=np.float64)
        return pose

    def test_compare_camera_pose_transform(self, nurec_reference_data):
        """Compare camera pose transforms with NuRec reference"""
        if nurec_reference_data is None:
            pytest.skip("No NuRec reference data available")

        errors = []
        for sample in nurec_reference_data.get('camera_poses', []):
            carla_pose = np.array(sample['carla_pose'])
            nurec_result = np.array(sample['nurec_pose'])

            # Use our transform
            our_result = CoordinateTransform.transform_pose_carla_to_dggt(carla_pose)

            # Compare position component
            pos_error = np.max(np.abs(our_result[:3, 3] - nurec_result[:3, 3]))
            # Compare rotation component (normalized)
            rot_error = np.max(np.abs(our_result[:3, :3] - nurec_result[:3, :3]))

            errors.append((pos_error, rot_error))

            assert np.allclose(our_result, nurec_result, atol=1e-6), \
                f"Mismatch in camera pose transform for sample {sample.get('id', 'unknown')}: pos_err={pos_error:.6e}, rot_err={rot_error:.6e}"

        # Report summary
        if errors:
            max_pos_err = max(e[0] for e in errors)
            max_rot_err = max(e[1] for e in errors)
            print(f"\nCamera pose transform comparison: max_pos_err={max_pos_err:.6e}, max_rot_err={max_rot_err:.6e}")

    def test_compare_dynamic_object_transform(self, nurec_reference_data):
        """Compare dynamic object pose transforms with NuRec reference"""
        if nurec_reference_data is None:
            pytest.skip("No NuRec reference data available")

        errors = []
        for sample in nurec_reference_data.get('dynamic_objects', []):
            carla_pose = np.array(sample['carla_pose'])
            nurec_result = np.array(sample['nurec_pose'])

            # Use our transform
            our_result = CoordinateTransform.transform_pose_carla_to_dggt(carla_pose)

            # Compare
            pos_error = np.max(np.abs(our_result[:3, 3] - nurec_result[:3, 3]))
            rot_error = np.max(np.abs(our_result[:3, :3] - nurec_result[:3, :3]))

            errors.append((pos_error, rot_error))

            assert np.allclose(our_result, nurec_result, atol=1e-6), \
                f"Mismatch in dynamic object pose transform for object {sample.get('track_id', 'unknown')}: pos_err={pos_error:.6e}, rot_err={rot_error:.6e}"

        # Report summary
        if errors:
            max_pos_err = max(e[0] for e in errors)
            max_rot_err = max(e[1] for e in errors)
            print(f"\nDynamic object transform comparison: max_pos_err={max_pos_err:.6e}, max_rot_err={max_rot_err:.6e}")

    def test_generate_comparison_report(self, nurec_reference_data, tmp_path):
        """Generate detailed comparison report"""
        if nurec_reference_data is None:
            pytest.skip("No NuRec reference data available")

        report_lines = ["# Coordinate Transform Comparison Report\n\n"]
        report_lines.append("Generated by test_nurec_comparison.py\n\n")

        # Camera poses section
        report_lines.append("## Camera Poses\n\n")
        camera_errors = []
        for sample in nurec_reference_data.get('camera_poses', []):
            carla_pose = np.array(sample['carla_pose'])
            nurec_result = np.array(sample['nurec_pose'])
            our_result = CoordinateTransform.transform_pose_carla_to_dggt(carla_pose)

            pos_error = np.max(np.abs(our_result[:3, 3] - nurec_result[:3, 3]))
            rot_error = np.max(np.abs(our_result[:3, :3] - nurec_result[:3, :3]))
            camera_errors.append((pos_error, rot_error))

            report_lines.append(f"- Sample {sample.get('id', 'unknown')}:\n")
            report_lines.append(f"  - Position error: {pos_error:.6e}\n")
            report_lines.append(f"  - Rotation error: {rot_error:.6e}\n")

        # Dynamic objects section
        report_lines.append("\n## Dynamic Objects\n\n")
        object_errors = []
        for sample in nurec_reference_data.get('dynamic_objects', []):
            carla_pose = np.array(sample['carla_pose'])
            nurec_result = np.array(sample['nurec_pose'])
            our_result = CoordinateTransform.transform_pose_carla_to_dggt(carla_pose)

            pos_error = np.max(np.abs(our_result[:3, 3] - nurec_result[:3, 3]))
            rot_error = np.max(np.abs(our_result[:3, :3] - nurec_result[:3, :3]))
            object_errors.append((pos_error, rot_error))

            report_lines.append(f"- Object {sample.get('track_id', 'unknown')}:\n")
            report_lines.append(f"  - Position error: {pos_error:.6e}\n")
            report_lines.append(f"  - Rotation error: {rot_error:.6e}\n")

        # Summary section
        report_lines.append("\n## Summary\n\n")
        all_errors = camera_errors + object_errors
        if all_errors:
            max_pos_err = max(e[0] for e in all_errors)
            max_rot_err = max(e[1] for e in all_errors)
            mean_pos_err = np.mean([e[0] for e in all_errors])
            mean_rot_err = np.mean([e[1] for e in all_errors])

            report_lines.append(f"- **Max position error**: {max_pos_err:.6e}\n")
            report_lines.append(f"- **Max rotation error**: {max_rot_err:.6e}\n")
            report_lines.append(f"- **Mean position error**: {mean_pos_err:.6e}\n")
            report_lines.append(f"- **Mean rotation error**: {mean_rot_err:.6e}\n")
            report_lines.append(f"- **All within tolerance (1e-5)**: {all(e[0] < 1e-5 and e[1] < 1e-5 for e in all_errors)}\n")

        # Write report
        report_path = tmp_path / "comparison_report.md"
        report_path.write_text("".join(report_lines))
        print(f"\nComparison report written to: {report_path}")

        # Final assertion
        assert all(e[0] < 1e-5 and e[1] < 1e-5 for e in all_errors), "Some transforms exceed tolerance"

    def test_basic_carla_to_dggt_roundtrip(self, sample_carla_pose):
        """Test roundtrip CARLA -> DGGT -> CARLA transformation"""
        # Transform to DGGT
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(sample_carla_pose)

        # Transform back to CARLA
        carla_back = CoordinateTransform.transform_pose_dggt_to_carla(dggt_pose)

        # Should match original (within numerical precision - 1e-6 for float64 operations)
        assert np.allclose(sample_carla_pose, carla_back, atol=1e-6), \
            f"Roundtrip failed: original vs recovered mismatch"

    def test_transform_identity_pose(self):
        """Test transformation of identity pose matrix"""
        identity_pose = np.eye(4, dtype=np.float64)

        # Transform to DGGT
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(identity_pose)

        # Check rotation part matches expected CARLA_TO_DGGT rotation
        expected_rot = CoordinateTransform.CARLA_TO_DGGT_ROTATION
        assert np.allclose(dggt_pose[:3, :3], expected_rot, atol=1e-10), \
            "Identity pose rotation should match CARLA_TO_DGGT_ROTATION"

    def test_transform_point_forward(self):
        """Test that CARLA forward vector transforms to DGGT forward (Z-axis)"""
        # CARLA forward = [1, 0, 0]
        carla_forward = np.array([1.0, 0.0, 0.0])

        dggt_point = CoordinateTransform.transform_point_carla_to_dggt(carla_forward)

        # DGGT forward is Z-axis: [0, 0, 1]
        expected_dggt_forward = np.array([0.0, 0.0, 1.0])
        assert np.allclose(dggt_point, expected_dggt_forward, atol=1e-10), \
            f"CARLA forward should map to DGGT Z-forward: got {dggt_point}"

    def test_transform_point_right(self):
        """Test that CARLA right vector transforms to DGGT right (X-axis)"""
        # CARLA right = [0, 1, 0]
        carla_right = np.array([0.0, 1.0, 0.0])

        dggt_point = CoordinateTransform.transform_point_carla_to_dggt(carla_right)

        # DGGT right is X-axis: [1, 0, 0]
        expected_dggt_right = np.array([1.0, 0.0, 0.0])
        assert np.allclose(dggt_point, expected_dggt_right, atol=1e-10), \
            f"CARLA right should map to DGGT X-right: got {dggt_point}"

    def test_transform_point_up(self):
        """Test that CARLA up vector transforms to DGGT down (negative Y-axis)"""
        # CARLA up = [0, 0, 1]
        carla_up = np.array([0.0, 0.0, 1.0])

        dggt_point = CoordinateTransform.transform_point_carla_to_dggt(carla_up)

        # DGGT Y is Down, so CARLA Up maps to negative Y: [0, -1, 0]
        expected_dggt_down = np.array([0.0, -1.0, 0.0])
        assert np.allclose(dggt_point, expected_dggt_down, atol=1e-10), \
            f"CARLA up should map to DGGT -Y (down): got {dggt_point}"


class TestCompareCameraPoseTransform:
    """Detailed camera pose transform tests"""

    @pytest.fixture
    def camera_test_data(self):
        """Sample camera pose test data"""
        return {
            'forward_looking': {
                'carla_pose': np.array([
                    [ 1.0,  0.0,  0.0,  10.0],
                    [ 0.0,  1.0,  0.0,   0.0],
                    [ 0.0,  0.0,  1.0,   2.0],
                    [ 0.0,  0.0,  0.0,   1.0]
                ]),
                'description': 'Camera looking forward, at (10, 0, 2) in CARLA'
            },
            'yawed_camera': {
                'carla_pose': np.array([
                    [ 0.0, -1.0,  0.0,   5.0],
                    [ 1.0,  0.0,  0.0,  10.0],
                    [ 0.0,  0.0,  1.0,   2.0],
                    [ 0.0,  0.0,  0.0,   1.0]
                ]),
                'description': 'Camera yawed 90 degrees left, at (5, 10, 2)'
            }
        }

    def test_forward_camera_transform(self, camera_test_data):
        """Test forward-looking camera pose"""
        pose = camera_test_data['forward_looking']['carla_pose']
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(pose)

        # Verify position transform
        # CARLA (10, 0, 2) -> DGGT: X=Y_carla=0, Y=-Z_carla=-2, Z=X_carla=10
        expected_pos = np.array([0.0, -2.0, 10.0])
        assert np.allclose(dggt_pose[:3, 3], expected_pos, atol=1e-10), \
            f"Position mismatch: expected {expected_pos}, got {dggt_pose[:3, 3]}"

    def test_yawed_camera_transform(self, camera_test_data):
        """Test yawed camera pose"""
        pose = camera_test_data['yawed_camera']['carla_pose']
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(pose)

        # Position: CARLA (5, 10, 2) -> DGGT: X=-10 (Y negated), Y=-2, Z=5
        # Note: undo_carla_coordinate_transform negates Y position before rotation
        expected_pos = np.array([-10.0, -2.0, 5.0])
        assert np.allclose(dggt_pose[:3, 3], expected_pos, atol=1e-10), \
            f"Position mismatch: expected {expected_pos}, got {dggt_pose[:3, 3]}"


class TestCompareDynamicObjectTransform:
    """Detailed dynamic object transform tests"""

    @pytest.fixture
    def vehicle_test_data(self):
        """Sample vehicle pose test data"""
        return {
            'stationary_vehicle': {
                'carla_pose': np.array([
                    [ 1.0,  0.0,  0.0,  50.0],
                    [ 0.0,  1.0,  0.0,   3.0],
                    [ 0.0,  0.0,  1.0,   0.5],
                    [ 0.0,  0.0,  0.0,   1.0]
                ]),
                'description': 'Vehicle at (50, 3, 0.5) facing forward'
            },
            'turning_vehicle': {
                'carla_pose': np.array([
                    [ 0.707, -0.707,  0.0,  30.0],
                    [ 0.707,  0.707,  0.0,  20.0],
                    [ 0.0,    0.0,    1.0,   0.5],
                    [ 0.0,    0.0,    0.0,   1.0]
                ]),
                'description': 'Vehicle turning 45 degrees at (30, 20, 0.5)'
            }
        }

    def test_stationary_vehicle_transform(self, vehicle_test_data):
        """Test stationary vehicle pose"""
        pose = vehicle_test_data['stationary_vehicle']['carla_pose']
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(pose)

        # Position: CARLA (50, 3, 0.5) -> DGGT: X=-3 (Y negated), Y=-0.5, Z=50
        # Note: undo_carla_coordinate_transform negates Y position before rotation
        expected_pos = np.array([-3.0, -0.5, 50.0])
        assert np.allclose(dggt_pose[:3, 3], expected_pos, atol=1e-10)

    def test_turning_vehicle_transform(self, vehicle_test_data):
        """Test turning vehicle pose"""
        pose = vehicle_test_data['turning_vehicle']['carla_pose']
        dggt_pose = CoordinateTransform.transform_pose_carla_to_dggt(pose)

        # Position: CARLA (30, 20, 0.5) -> DGGT: X=-20 (Y negated), Y=-0.5, Z=30
        # Note: undo_carla_coordinate_transform negates Y position before rotation
        expected_pos = np.array([-20.0, -0.5, 30.0])
        assert np.allclose(dggt_pose[:3, 3], expected_pos, atol=1e-10)


class TestGenerateComparisonReport:
    """Report generation tests"""

    def test_report_structure(self, tmp_path):
        """Test that report has correct structure"""
        # Create minimal reference data
        ref_data = {
            'camera_poses': [
                {
                    'id': 'test_001',
                    'carla_pose': [[1,0,0,10],[0,1,0,0],[0,0,1,2],[0,0,0,1]],
                    'nurec_pose': [[0,1,0,0],[0,0,-1,-2],[1,0,0,10],[0,0,0,1]]
                }
            ],
            'dynamic_objects': []
        }

        # Save temporary reference
        ref_dir = tmp_path / "nurec_reference"
        ref_dir.mkdir()
        ref_file = ref_dir / "coordinate_transforms.json"
        with open(ref_file, 'w') as f:
            json.dump(ref_data, f)

        # Generate report
        report_lines = ["# Coordinate Transform Comparison Report\n\n"]
        for sample in ref_data['camera_poses']:
            carla_pose = np.array(sample['carla_pose'])
            nurec_result = np.array(sample['nurec_pose'])
            our_result = CoordinateTransform.transform_pose_carla_to_dggt(carla_pose)

            error = np.max(np.abs(our_result - nurec_result))
            report_lines.append(f"- Sample {sample['id']}: error = {error:.6e}\n")

        report_path = tmp_path / "test_report.md"
        report_path.write_text("".join(report_lines))

        # Verify report exists and has content
        assert report_path.exists()
        content = report_path.read_text()
        assert "Coordinate Transform Comparison Report" in content
        assert "test_001" in content